jobs:
- job: BuildBaseExe
  timeoutInMinutes: 120
  strategy:
    matrix:
      ubuntu:
        imageName: 'ubuntu-16.04'
      mac:
        imageName: 'macos-10.14'
#      windows_2017:
#        imageName: 'vs2017-win2016'
#      windows_2015:
#        imageName: 'vs2017-win2016'
#      alpine:
#        imageName: 'ubuntu-16.04'
  pool:
    vmImage: $(imageName)
  steps:
  - task: ShellScript@2
    displayName: Install dependencies
    inputs:
      scriptPath: ./install_build_tools.sh
  - script: make all
    displayName: Build all
  - script: make test
    displayName: Run tests
