name: AppScope

on: [push]

jobs:

  build-scope:
    name: Build Scope
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.15
      - name: Install Dependencies
        run: |
            ./install_build_tools.sh
            make deps
      - name: Build
        run: make all
      - name: Unit Tests
        run: make test
      - name: Archive Built Binaries
        uses: actions/upload-artifact@v2
        with:
          name: built-binaries
          path: |
            lib/linux/libscope.so
            bin/linux/scope
            bin/linux/ldscope
          retention-days: 5
      - name: Push Artifacts to S3 Bucket for CDN
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
          CF_DISTRIBUTION_ID: ${{ secrets.CF_DISTRIBUTION_ID }}
        run: ./deploy.sh
      - name: Build & Push Container Image to Docker Hub
        if: startsWith(github.ref, 'refs/tags/v')
        env:
          SCOPECI_TOKEN: ${{ secrets.SCOPECI_TOKEN }}
        run: ./docker/build.sh

  integration-test:
    strategy:
      matrix: 
        test: [bash, detect_proto, elastic, gogen, go_2, go_3, go_4, go_5, go_6, go_7, go_8, go_9, go_10, go_11, go_12, go_13, go_14, go_15, go_16, java6, java7, java8, java9, java10, java11, java12, java13, java14, kafka, logstream, nginx, oracle-java6, oracle-java7, oracle-java8, oracle-java9, oracle-java10, oracle-java11, oracle-java12, oracle-java13, oracle-java14, splunk, syscalls, tls]
      fail-fast: false
    name: "Test: ${{ matrix.test }}"
    runs-on: ubuntu-latest
    needs: build-scope
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Download Built Binaries
        uses: actions/download-artifact@v2
        with:
          name: built-binaries
      - name: Run Test
        run: |
            chmod +x bin/linux/* lib/linux/*
            make -C test/testContainers ${{ matrix.test }}
      - name: Save Image
        if: github.ref == 'refs/heads/master'
        env:
            DOCKER_HUB_USER: ${{ secrets.DOCKER_HUB_USER }}
            DOCKER_HUB_PASS: ${{ secrets.DOCKER_HUB_PASS }}
        run: make -C test/testContainers ${{ matrix.test }}-push
