name: website
on:
  push:
    branches:
      - master
      - staging
  pull_request:
    branches:
      - master
      - staging
jobs:
  website:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: "Website Deploy"
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
        run: ./website/deploy.sh
